# Generated by Django 4.2 on 2023-10-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocomum',
            name='nome',
        ),
        migrations.AddField(
            model_name='usuariocomum',
            name='nome_completo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usuariocomum',
            name='data_nasc',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuariocomum',
            name='endereco',
            field=models.TextField(null=True),
        ),
    ]
