# Generated by Django 4.2 on 2023-10-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroUser', '0002_remove_usuariocomum_nome_usuariocomum_nome_completo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocomum',
            name='nome_completo',
        ),
    ]
